import childProcess from 'child_process'
import type { IApi } from 'umi'

export default (api: IApi) => {
  api.describe({
    key: 'buildInfo',
    config: {
      default: {
        debug: false,
        buildInfoKey: 'builInfo',
      },

      schema(Joi) {
        return Joi.object({
          debug: Joi.boolean().required(),
          buildInfoKey: Joi.string(),
        })
      },
    },
  })

  api.addHTMLScripts(() => {
    // 构建时间
    const buildTime = new Date().toLocaleString()
    // 提取最后一次提交记录的信息
    const lastCommit = childProcess.execSync('git log --format="[%h]: %s, %cd" -n 1').toString().trim().replace(/['"]/g, "");

    const { debug, buildInfoKey } = api.config.buildInfo

    if (api.env === 'production') {
      if (debug) {
        api.logger.info(`buildTime：${buildTime}`)
        api.logger.info(`lastCommit：${lastCommit}`)
      }

      return `
      /* ## THIS CONTENT WAS GENERATED BY UMI BUILD_INFO PLUGIN ## */

      const builInfo = Object.create(null);
      builInfo.buildTime = '${buildTime}';
      builInfo.lastCommit = '${lastCommit}';

      window.${buildInfoKey} = builInfo
      `
    }

    return ''
  })
}
